trailingComma: 'es5'
useTabs: false
# tabWidth: 4
tabWidth: 2
singleQuote: true
semi: false
quoteProps: 'consistent'
bracketSpacing: false
arrowParens: 'always'
endOfLine: 'lf'
vueIndentScriptAndStyle: true
printWidth: 240
